# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpacexData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpacexData
  pod "ImageSlideshow/Kingfisher"
  pod 'IQKeyboardManagerSwift'
  pod 'RxSwift', '~> 4.0'
  pod 'Alamofire', '~> 4.9.0'
  pod 'JGProgressHUD'
  pod 'SwiftDate'
  pod 'PopupDialog'
  
  target 'SpacexDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpacexDataUITests' do
    # Pods for testing
  end

end
